<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\ThinkMeta.Devices.Bluetooth.HeartRate.Windows\ThinkMeta.Devices.Bluetooth.HeartRate.Windows.csproj" />
    </ItemGroup>
</Project>
